name: build and push

on:
  workflow_call:
    inputs:
      repository:
        description: 'A ECR repository name to push image.'
        required: true
        type: string
      context:
        description: 'Build`s context is the set of files located in the specified PATH or URL.'
        required: false
        default: '.'
        type: string
      assume_role:
        description: 'An assume_role arn to deploy resources on aws.'
        required: true
        type: string
      aws_region:
        description: 'An aws region name to deploy resouces.'
        required: true
        type: string
    
    outputs:
      imageHash:
        description: "The build image hash."
        value: ${{ jobs.docker.outputs.imageHash }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      imageHash: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.assume_role }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.repository }}
        with:
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:latest"
          context: ${{ inputs.context }}
          provenance: false