name: load image hash

on:
  workflow_call:
    inputs:
      artifact:
        description: 'An artifact name.'
        required: true
        type: string
    outputs:
      imageHash:
        description: "The build image hash."
        value: ${{ jobs.load_image_hash.outputs.imageHash }}

jobs:
  load_image_hash:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      imageHash: ${{ steps.output.outputs.image_hash }}
    steps:
      - name: Get run id
        id: get_run_id
        run: |
          wf_history=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/workflows/check.yml/runs?per_page=1&status=success)
          run_id=$(echo $wf_history | jq -r '.workflow_runs[0] | .id' )
          echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Load hash
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          github-token: ${{ github.token }}
      - name: Output hash
        id: output
        run: |
          image_hash=$(cat image_hash.txt)
          echo "image_hash=$image_hash" >> "$GITHUB_OUTPUT"