name: review remove

on:
  workflow_dispatch:

jobs:
  convert_head_ref_name:
    uses: ./.github/workflows/convert_to_artifact_name.yml
    with:
      org: ${{ github.ref_name }}

  serverless_deploy:
    needs: convert_head_ref_name
    uses: ./.github/workflows/remove.yml
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      env: dev
      artifact: ${{ needs.convert_head_ref_name.outputs.converted }}
      assume_role: arn:aws:iam::394895440631:role/faas-t2022096-github-oidc
      aws_region: ap-northeast-1
      app_domain: -api-t2022096.faas-handson.cnt-tdc.com
